---
title: "Kernel Principal Component Analysis (PCA)"
author: "Sasha Ajay Malkani"
date: "2025-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the dataset

```{r Importing the dataset}
dataset = read.csv('Social_Network_Ads.csv')
dataset = dataset[3:5]
head(dataset)

```

## Encoding the target feature as factor
```{r Encoding the target feature as factor}
dataset$Purchased = factor(dataset$Purchased, levels = c(0, 1))

```

## Splitting the dataset into the Training set and Test set

```{r Splitting the dataset into the Training set and Test set}
# install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
head(training_set)
test_set = subset(dataset, split == FALSE)
head(test_set)
```

## Feature Scaling

```{r Feature Scaling}
training_set[, 1:2] = scale(training_set[, 1:2])
head(training_set)
test_set[, 1:2] = scale(test_set[, 1:2])
head(test_set)

```

## Applying Kernel PCA

```{r Applying Kernel PCA}
# install.packages("kernlab")
library(kernlab)
kpca = kpca(~., data = training_set[-3], kernel = 'rbfdot', features = 2)
training_set_pca = as.data.frame(predict(kpca, training_set))
head(training_set_pca)
training_set_pca$Purchased = training_set$Purchased
head(training_set_pca)
test_set_pca = as.data.frame(predict(kpca, test_set))
head(test_set_pca)
test_set_pca$Purchased = test_set$Purchased
head(test_set_pca)

```

## Fitting Logistic Regression to the Training set

```{r Fitting Logistic Regression to the Training set}
classifier = glm(formula = Purchased ~ .,
                 family = binomial,
                 data = training_set_pca)
summary(classifier)

```

## Predicting the Test set results

```{r Predicting the Test set results}
prob_pred = predict(classifier, type = 'response', newdata = test_set_pca[-3])
head(prob_pred)
y_pred = ifelse(prob_pred > 0.5, 1, 0)
head(y_pred)
head(test_set$Purchased)


```

## Making the Confusion Matrix

```{r Making the Confusion Matrix}
cm = table(test_set_pca[, 3], y_pred)
cm

```

## Visualising the Training set results

```{r Visualising the Training set results}
library(ElemStatLearn)
set = training_set_pca
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('V1', 'V2')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3],
     main = 'Logistic Regression (Training set)',
     xlab = 'PC1', ylab = 'PC2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'dodgerblue', 'salmon'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'dodgerblue3', 'salmon3'))
```

## Visualising the Test set results

```{r Visualising the Test set results}
library(ElemStatLearn)
set = test_set_pca
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('V1', 'V2')
prob_set = predict(classifier, type = 'response', newdata = grid_set)
y_grid = ifelse(prob_set > 0.5, 1, 0)
plot(set[, -3],
     main = 'Logistic Regression (Test set)',
     xlab = 'PC1', ylab = 'PC2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'dodgerblue', 'salmon'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'dodgerblue3', 'salmon3'))

```


















