---
title: "Linear Discriminant Analysis (LDA)"
author: "Sasha Ajay Malkani"
date: "2025-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the dataset

```{r Importing the dataset}
dataset = read.csv('Wine.csv')
```

## Splitting the dataset into the Training set and Test set

```{r Splitting the dataset into the Training set and Test set}
# install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(dataset$Customer_Segment, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
```

## Feature Scaling

```{r Feature Scaling}
training_set[-14] = scale(training_set[-14])
head(training_set)
test_set[-14] = scale(test_set[-14])
head(test_set)
```

## Applying LDA

```{r Applying LDA}
library(MASS)
lda = lda(formula = Customer_Segment ~ ., data = training_set)
training_set = as.data.frame(predict(lda, training_set))
head(training_set)
training_set = training_set[c(5, 6, 1)]
head(training_set)
test_set = as.data.frame(predict(lda, test_set))
head(test_set)
test_set = test_set[c(5, 6, 1)]
head(test_set)
```

## Fitting SVM to the Training set

```{r Fitting SVM to the Training set}
# install.packages('e1071')
library(e1071)
classifier = svm(formula = class ~ .,
                 data = training_set,
                 type = 'C-classification',
                 kernel = 'linear')
summary(classifier)
```

## Predicting the Test set results

```{r Predicting the Test set results}
y_pred= predict(classifier, type = 'response', newdata = test_set[-3])
print(y_pred)
print(test_set$class)
```

## Making the Confusion Matrix

```{r Making the Confusion Matrix}
cm = table(test_set[, 3], y_pred)
cm
```

## Visualising the Training set results

```{r Visualising the Training set results}
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('x.LD1', 'x.LD2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3],
     main = 'SVM (Training set)',
     xlab = 'LD1', ylab = 'LD2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 2, 'deepskyblue', ifelse(y_grid == 1, 'springgreen3', 'tomato')))
points(set, pch = 21, bg = ifelse(set[, 3] == 2, 'blue3', ifelse(set[, 3] == 1, 'green4', 'red3')))

```


## Visualising the Test set results

```{r Visualising the Test set results}
library(ElemStatLearn)
set = test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('x.LD1', 'x.LD2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3], main = 'SVM (Test set)',
     xlab = 'LD1', ylab = 'LD2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 2, 'deepskyblue', ifelse(y_grid == 1, 'springgreen3', 'tomato')))
points(set, pch = 21, bg = ifelse(set[, 3] == 2, 'blue3', ifelse(set[, 3] == 1, 'green4', 'red3')))

```



