---
title: "XGBoost"
author: "Sasha Ajay Malkani"
date: "2025-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the dataset

```{r Importing the dataset}
dataset = read.csv('Churn_Modelling.csv')
head(dataset)
dataset = dataset[4:14]
head(dataset)

```

## Encoding the categorical variables as factors

```{r Encoding the categorical variables as factors}
dataset$Geography = as.numeric(factor(dataset$Geography,
                                      levels = c('France', 'Spain', 'Germany'),
                                      labels = c(1, 2, 3)))
dataset$Gender = as.numeric(factor(dataset$Gender,
                                   levels = c('Female', 'Male'),
                                   labels = c(1, 2)))
head(dataset)
```

## Splitting the dataset into the Training set and Test set

```{r Splitting the dataset into the Training set and Test set}
# install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(dataset$Exited, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
head(training_set)
test_set = subset(dataset, split == FALSE)
head(test_set)

```

## Fitting XGBoost to the Training set

```{r Fitting XGBoost to the Training set}
# install.packages("xgboost")
library(xgboost)
classifier = xgboost(data = as.matrix(training_set[-11]), label = training_set$Exited, nrounds = 10)

summary(classifier)
```

## Predicting the Test set results

```{r Predicting the Test set results}
y_pred = predict(classifier, newdata = as.matrix(test_set[-11]))
y_pred = ifelse(y_pred >= 0.5, 1, 0)
head(y_pred)
head(test_set$Exited)

```

## Making the Confusion Matrix

```{r Making the Confusion Matrix}
cm = table(test_set[, 11], y_pred)
print(cm)
accuracy_test = (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
print(paste('acurracy for the test set:', accuracy_test))
```

## Applying k-Fold Cross Validation

```{r Applying k-Fold Cross Validation}
# install.packages('caret')
library(caret)
folds = createFolds(dataset$Exited, k = 10)
cv = lapply(folds, function(x) {
  training_fold = dataset[-x, ]
  test_fold = dataset[x, ]
  classifier = xgboost(data = as.matrix(training_fold[-11]), label = training_fold$Exited, nrounds = 10)
  y_pred = predict(classifier, newdata = as.matrix(test_fold[-11]))
  y_pred = (y_pred >= 0.5)
  cm = table(test_fold[, 11], y_pred)
  accuracy = (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] + cm[1,2] + cm[2,1])
  return(accuracy)
})
accuracy = mean(as.numeric(cv))
print(paste('average accuracy across the 10 folds:', accuracy))
std_dev = sd(as.numeric(cv))
print(paste('average standard deviation across the 10 folds:', std_dev))
```

