---
title: "Support Vector Regression"
author: "Sasha Ajay Malkani"
date: "2025-06-03"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## importing the dataset

```{r importing the dataset}
dataset = read.csv('Position_Salaries.csv')

print(dataset)
```

## Reset dataset

```{r Reset dataset}

dataset = dataset[2:3]

print(dataset)
```

## Fitting SVR to the dataset

```{r Fitting SVR to the dataset}
# install.packages('e1071')
library(e1071)
regressor = svm(formula = Salary ~ ., 
                data = dataset, 
                type = 'eps-regression')

summary(regressor)

```

## Predicting a new result 

```{r Predicting a new result}
y_pred = predict(regressor, data.frame(Level = 6.5))

print(y_pred)

```

## Visualizing the SVR results

```{r Visualizing the SVR results}
# install.packages('ggplot2')
library(ggplot2)
ggplot() + 
  geom_point(aes(x = dataset$Level, y = dataset$Salary), 
             colour = 'red') +
  geom_line(aes(x = dataset$Level, y = predict(regressor, newdata = dataset)), 
            colour = 'blue') +
  ggtitle('Truth or Bluff (SVR)') +
  xlab('Level') +
  ylab('Salary')

```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
