---
title: "Decision Tree Regression"
author: "Sasha Ajay Malkani"
date: "2025-06-04"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the Dataset

```{r Importing the Dataset}
dataset = read.csv('Position_Salaries.csv')

print(dataset)
```

## Reset the dataset

```{r Reset the dataset}

dataset = dataset[2:3]

print(dataset)
```

## Fitting Regression Model to the dataset

```{r Fitting Regression Model to the dataset}
#install.packages('rpart')
library(rpart)

regressor = rpart(formula = Salary ~ ., 
                  data = dataset,
                  control = rpart.control(minsplit = 1))

summary(regressor)

```

## Predicting a new result

```{r Predicting a new result}

y_pred = predict(regressor, data.frame(Level = 6.5))

print(y_pred)

```

## Visualizing the Regression Model results (for higher resolution and smoother curve)


```{r Visualizing the Regression Model results}
# install.packages('ggplot2')
library(ggplot2)
x_grid = seq(min(dataset$Level), max(dataset$Level), 0.01)
ggplot() +
  geom_point(aes(x = dataset$Level, y = dataset$Salary),
             colour = 'red') +
  geom_line(aes(x = x_grid, y = predict(regressor, newdata = data.frame(Level = x_grid))),
            colour = 'blue') +
  ggtitle('Truth or Bluff (Decision Tree Regression)') +
  xlab('Level') +
  ylab('Salary')



```











Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
