---
title: "K Means Clustering"
author: "Sasha Ajay Malkani"
date: "2025-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the dataset

```{r Importing the dataset}
dataset = read.csv('mall.csv')
head(dataset)
```

## Reset the dataset


```{r Reset the dataset}
X = dataset[4:5]
head(X)
```

## Using the elbow method to find the optimal number of clusters

```{r Using the elbow method to find the optimal number of clusters}
set.seed(6)
wcss = vector()
for (i in 1:10) wcss[i] = sum(kmeans(X, i)$withinss)
plot(1:10, wcss, type = "b", main = paste("Clusters of clients"), xlab = "Number of Clusters", ylab = "WCSS")

```

## Applying K-means to the mall dataset


```{r Applying K-means to the mall dataset}
set.seed(29)
kmeans = kmeans(X, 5, iter.max = 300, nstart = 10)
summary(kmeans)

```

## Visualizing the Clusters

```{r Visualizing the Clusters}
library(cluster)
clusplot(X,
         kmeans$cluster,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Clusters of clients"),
         xlab = "Annual Income",
         ylab = "Spending Score")

```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
