---
title: "Hierarchical Clustering"
author: "Sasha Ajay Malkani"
date: "2025-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the dataset

```{r Importing the dataset}
dataset = read.csv('mall.csv')
head(dataset)

```

## Creating Matrix of features X

```{r Creating Matrix of features X}
X = dataset[4:5]
head(X)

```

## Using the dendrogram to find the optimal number of clusters

```{r Using the dendrogram to find the optimal number of clusters}
dendrogram = hclust(dist(X, method ="euclidean"), method = "ward.D")
plot(dendrogram,
     main = paste("Dendrogram"),
     xlab = "Customers",
     ylab = "Euclidean distances")

```

## Fitting hierarchical clustering to the mall dataset

```{r Fitting hierarchical clustering to the mall dataset}
hc = hclust(dist(X, method ="euclidean"), method = "ward.D")
y_hc = cutree(hc, k = 5)
y_hc

```

## Visualising the clusters

```{r Visualising the clusters}
library(cluster)
clusplot(X,
         y_hc,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Clusters of clients"),
         xlab = "Annual Income",
         ylab = "Spending Score")

```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
