---
title: "Data Preprocessing"
author: "Sasha Ajay Malkani"
date: "2025-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the Dataset

```{r Importing Dataset}
dataset = read.csv('Data.csv')
print(dataset)
```

## Taking care of missing data



```{r Taking care of missing data}
dataset$Age = ifelse(is.na(dataset$Age), 
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)),
                     dataset$Age)

dataset$Salary = ifelse(is.na(dataset$Salary), 
                     ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)),
                     dataset$Salary)

print(dataset)
```
## Encoding Categorical Data

```{r Encoding Categorical data}
dataset$Country = factor(dataset$Country, 
                         levels = c('France', 'Spain', 'Germany'), 
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased, 
                         levels = c('No', 'Yes'), 
                         labels = c(0, 1))
print(dataset)

```

## Splitting the dataset into Training and Test data set

```{r Splitting the dataset into Training and Test data sets}

library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

print(training_set)
print(test_set)

```

## Feature Scaling

```{r Feature Scaling}
training_set[, 2:3] = scale(training_set[, 2:3])
test_set[, 2:3] = scale(test_set[, 2:3])

print(training_set)
print(test_set)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
